<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Model\System\Config\Source;

/**
 * Class DynamicShipping
 */
class DynamicShipping implements \Magento\Framework\Option\ArrayInterface
{
    const TYPE_DEFAULT = 0;
    const TYPE_BY_RATE_WITH_LARGEST_TOTAL = 1;
    const TYPE_BY_RATE_WITH_HIGHEST_RATE = 2;

    /**
     * @var array
     */
    protected $options = null;

    /**
     * @return array
     */
    public function toOptionArray()
    {
        if ($this->options === null) {
            $options = [
                [
                    'value' => self::TYPE_DEFAULT,
                    'label' => __('No')
                ],
                [
                    'value' => self::TYPE_BY_RATE_WITH_LARGEST_TOTAL,
                    'label' => __('Use the tax class with largest total')
                ],
                [
                    'value' => self::TYPE_BY_RATE_WITH_HIGHEST_RATE,
                    'label' => __('Use the tax class with the highest rate')
                ]
            ];

            $this->options = $options;
        }

        return $this->options;
    }
}
