<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Model\System\Config\Source;

/**
 * Class Interfaces
 */
class Interfaces implements \Magento\Framework\Option\ArrayInterface
{
    const VIES = 'Vies';
    const BZST = 'Bzst';

    /**
     * Provides select options
     * @return array
     */
    public function toOptionArray()
    {
        return [
            ['value' => self::VIES, 'label' => __('VIES')],
            //['value' => self::BZST, 'label' => __('BZSt (Germany only)')]
        ];
    }

    /**
     * Get options in "key-value" format
     *
     * @return array
     */
    public function toArray()
    {
        return [
            self::VIES => "VIES",
            //self::BZST => "BZSt",
        ];
    }
}
