<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Model\System\Config\Source;

/**
 * Class ValidationOptions
 */
class ValidationOptions implements \Magento\Framework\Data\OptionSourceInterface
{
    /**
     * Options getter
     *
     * @return array
     */
    public function toOptionArray()
    {
        return [
            [
                'value' => '',
                'label' => __('Optional')
            ],
            [
                'value' => 'valid-vat-if-specified',
                'label' => __('Optional, but require a valid VAT number when filled')
            ],
            [
                'value' => 'valid-vat-required',
                'label' => __('Require a valid VAT number (validated through the validation service)')
            ],
            [
                'value' => 'valid-vat-if-company-specified',
                'label' => __('Require a valid VAT number, when the company field is filled')
            ],
            [
                'value' => 'required-entry',
                'label' => __('Required (accept any value)')
            ]
        ];
    }
}
