<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Plugin;

use Magento\Framework\Exception\CouldNotSaveException;

/**
 * Class OrderManagement
 */
class OrderManagement
{
    /**
     * @var \Geissweb\Euvat\Helper\Configuration
     */
    private $configHelper;

    /**
     * @var \Geissweb\Euvat\Logger\Logger
     */
    private $logger;

    /**
     * @var \Geissweb\Euvat\Helper\Functions
     */
    private $functionsHelper;

    /**
     * @var \Geissweb\Euvat\Model\ValidationRepository
     */
    private $validationRepository;

    /**
     * @var \Geissweb\Euvat\Model\Validation
     */
    private $validationInterface;
    /**
     * @var \Magento\Sales\Api\Data\OrderStatusHistoryInterfaceFactory
     */
    private $orderStatusHistoryFactory;
    /**
     * @var \Magento\Sales\Api\OrderStatusHistoryRepositoryInterface
     */
    private $orderStatusHistoryRepository;

    /**
     * OrderManagement constructor.
     *
     * @param \Geissweb\Euvat\Helper\Configuration       $configHelper
     * @param \Geissweb\Euvat\Helper\Functions           $functionsHelper
     * @param \Geissweb\Euvat\Model\ValidationRepository $validationRepository
     * @param \Geissweb\Euvat\Model\Validation           $validationInterface
     * @param \Geissweb\Euvat\Logger\Logger              $logger
     */
    public function __construct(
        \Geissweb\Euvat\Helper\Configuration $configHelper,
        \Geissweb\Euvat\Helper\Functions $functionsHelper,
        \Geissweb\Euvat\Model\ValidationRepository $validationRepository,
        \Geissweb\Euvat\Model\Validation $validationInterface,
        \Geissweb\Euvat\Logger\Logger $logger,
        \Magento\Sales\Api\Data\OrderStatusHistoryInterfaceFactory $orderStatusHistoryFactory,
        \Magento\Sales\Api\OrderStatusHistoryRepositoryInterface $orderStatusHistoryRepository
    ) {
        $this->configHelper = $configHelper;
        $this->logger = $logger;
        $this->functionsHelper = $functionsHelper;
        $this->validationRepository = $validationRepository;
        $this->validationInterface = $validationInterface;
        $this->orderStatusHistoryFactory = $orderStatusHistoryFactory;
        $this->orderStatusHistoryRepository = $orderStatusHistoryRepository;
    }

    /**
     * Assigns customer group to guest order
     *
     * @param \Magento\Sales\Api\OrderManagementInterface $subject
     * @param \Magento\Sales\Api\Data\OrderInterface      $order
     *
     * @return \Magento\Sales\Api\Data\OrderInterface[]
     */
    public function beforePlace(
        \Magento\Sales\Api\OrderManagementInterface $subject,
        \Magento\Sales\Api\Data\OrderInterface $order
    ) {
        $this->logger->debug("beforePlaceOrder START orderId = " . $order->getEntityId());

        if ($order->getCustomerIsGuest()
            && $this->configHelper->getUseGroupAssignment()
            && $this->configHelper->isAssignCustomerGroupToGuestOrder()
        ) {
            try {
                $address = $this->_getAddressFromOrder($order);
                if ($address == false || $address == null) {
                    $this->logger->debug("beforePlaceOrder NO address found.");
                    return [$order];
                }

                $vatId = $address->getVatId();
                if (!empty($vatId)) {
                    /** @var \Geissweb\Euvat\Api\Data\ValidationInterface $validation */
                    $validation = $this->validationRepository->getByVatId($vatId);
                } else {
                    $validation = $this->validationInterface;
                }

                // Assign customer group to guest order
                $customerGroupForOrder = $this->functionsHelper->getCustomerGroup($address, $validation);
                $this->logger->debug("beforePlaceOrder Setting group_id: " . $customerGroupForOrder);
                $order->setCustomerGroupId($customerGroupForOrder);
            } catch (\Exception $e) {
                $this->logger->critical($e);
            }
        }

        $this->logger->debug("beforePlaceOrder END");

        return [$order];
    }

    /**
     * @param \Magento\Sales\Api\OrderManagementInterface $subject
     * @param \Magento\Sales\Api\Data\OrderInterface      $order
     *
     * @return \Magento\Sales\Api\Data\OrderInterface
     */
    public function afterPlace(
        \Magento\Sales\Api\OrderManagementInterface $subject,
        \Magento\Sales\Api\Data\OrderInterface $order
    ) {
        $this->logger->debug("AfterPlaceOrder START orderId = " . $order->getEntityId());
        try {
            $address = $this->_getAddressFromOrder($order);
            if ($address == false || $address == null) {
                $this->logger->debug("AfterPlaceOrder NO address found.");
                return $order;
            }

            $vatId = $address->getVatId();
            if (!empty($vatId)) {
                /** @var \Geissweb\Euvat\Api\Data\ValidationInterface $validation */
                $validation = $this->validationRepository->getByVatId($vatId);
                if ($validation instanceof \Geissweb\Euvat\Api\Data\ValidationInterface) {
                    // Add order comment with VAT validation data
                    $comment = $this->_compileOrderComment($validation);
                    if (!empty($comment)) {
                        $this->logger->debug("AfterPlaceOrder Adding comment: " . $comment);

                        /** @var \Magento\Sales\Api\Data\OrderStatusHistoryInterface $statusHistory */
                        $statusHistory = $this->orderStatusHistoryFactory->create();
                        //$statusHistory->setEntityId($order->getEntityId());
                        $statusHistory->setParentId($order->getEntityId());
                        $statusHistory->setEntityName('order');
                        $statusHistory->setComment($comment);
                        $statusHistory->setIsVisibleOnFront(0);
                        $statusHistory->setIsCustomerNotified(0);
                        $this->orderStatusHistoryRepository->save($statusHistory);
                    }
                }
            }
        } catch (CouldNotSaveException $e) {
            $this->logger->critical($e);
        }

        $this->logger->debug("AfterPlaceOrder END");

        return $order;
    }

    /**
     * @param $order
     *
     * @return bool|\Magento\Sales\Api\Data\OrderAddressInterface
     */
    private function _getAddressFromOrder($order)
    {
        $vatBasedOn = $this->configHelper->getVatBasedOn();
        if ($vatBasedOn == 'shipping' && $order->getIsNotVirtual()) {
            $address = $order->getShippingAddress();
        } else {
            $address = $order->getBillingAddress();
        }

        if (!$address instanceof \Magento\Sales\Api\Data\OrderAddressInterface) {
            $this->logger->debug("address, getting again from order");
            return $this->functionsHelper->getBasedOnAddressFromOrder($order, $vatBasedOn);
        }

        return $address;
    }

    /**
     * @param \Geissweb\Euvat\Api\Data\ValidationInterface $validation
     *
     * @return string
     */
    private function _compileOrderComment($validation)
    {
        $vatId = $validation->getVatId();
        $vatTraderName = $validation->getVatTraderName();
        $vatTraderAddress = $validation->getVatTraderAddress();
        $vatIsValid = $validation->getVatIsValid();
        $vatReqSuccess = $validation->getVatRequestSuccess();
        $vatReqId = $validation->getVatRequestId();

        $comment = '';
        $comment .= __('VAT number') . ": " . $vatId . "<br/>";
        if (!empty($vatTraderName)) {
            $comment .= __('VAT Trader Name') . ": " . $vatTraderName . "<br/>";
        }
        if (!empty($vatTraderAddress)) {
            $comment .= __('VAT Trader Address') . ": " . $vatTraderAddress . "<br/>";
        }
        $comment .= __('VAT number is') . ": ";
        $comment .= ($vatIsValid) ? __('valid') : __('invalid');
        $comment .= "<br/>";
        $comment .= __('VAT request success') . ": ";
        $comment .= ($vatReqSuccess) ? __('Yes') : __('No');
        $comment .= "<br/>";
        if ($vatReqSuccess && !empty($vatReqId)) {
            $comment .= __('VAT request identifier') . ": " . $vatReqId;
        }

        return $comment;
    }
}
