/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

var config = {
    config: {
        mixins: {
            'Magento_Checkout/js/model/cart/cache': {
                'Geissweb_Euvat/js/mixin/model-cart-cache-mixin': true
            },
            'mage/validation': {
                'Geissweb_Euvat/js/mixin/vat-field-form-validation': true
            },
            'Magento_Ui/js/lib/validation/validator': {
                'Geissweb_Euvat/js/mixin/vat-field-form-validation-ui': true
            }
        }
    },
    paths: {
        'euvatQueue': 'Geissweb_Euvat/js/queue'
    },
    map: {
        '*': {
            'Magento_Checkout/template/shipping-address/address-renderer/default':
                'Geissweb_Euvat/template/shipping-address/address-renderer/default-with-vatid',

            'Magento_Checkout/template/shipping-information/address-renderer/default':
                'Geissweb_Euvat/template/shipping-information/address-renderer/default-with-vatid',

            'Magento_Checkout/template/billing-address/details':
                'Geissweb_Euvat/template/billing-address/details-with-vatid'
        }
    }
};
