<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Observer\Adminhtml;

use Geissweb\Euvat\Helper\Configuration;
use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\Event\Observer as EventObserver;

/**
 * Class ConfigObserver
 */
class ConfigObserver implements ObserverInterface
{
    /**
     * @var Configuration
     */
    public $configHelper;

    /**
     * Init
     * @param Configuration $configHelper
     */
    public function __construct(
        Configuration $configHelper
    ) {
        $this->configHelper = $configHelper;
    }

    /**
     * Run Observer
     *
     * @param EventObserver $observer
     *
     * @return void
     * @throws \Magento\Framework\Exception\FileSystemException
     */
    public function execute(EventObserver $observer)
    {
        $this->configHelper->registerInstallation();
    }
}
