/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

/**
 * Thanks to http://stackoverflow.com/users/561731/neal
 */

define([
    'jquery'
], function ($) {
    "use strict";

    return {

        running: false,
        queue: [],

        run: function () {
            if (!this.running) {
                this.next();
            }
        },

        addFunction: function (callback) {
            var self = this;
            this.queue.push(function () {
                $.when(callback()).done(function () {
                    self.next();
                });
            });
            return this;
        },

        next: function () {
            this.running = false;
            var shift = this.queue.shift();
            if (shift) {
                this.running = true;
                shift();
            }
        }

    };

});