/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

define([
    'Magento_Checkout/js/model/quote',
    'Magento_Checkout/js/model/cart/totals-processor/default',
    'Magento_Checkout/js/model/checkout-data-resolver',
    'Magento_Checkout/js/model/shipping-rate-registry'
], function (
    Quote,
    TotalsProcessor,
    DataResolver,
    ShippingRateRegistry
) {
    "use strict";

    return {

        /**
         * Needed for Mageplaza checkout
         */
        addresses: function() {
            DataResolver.resolveShippingAddress();
            DataResolver.applyShippingAddress(DataResolver.resolveEstimationAddress());
            DataResolver.resolveBillingAddress();
            DataResolver.applyBillingAddress();
        },

        /**
         * Amasty checkout has this function and it is needed to call
         * because otherwise shipping methods do not reload
         */
        reloadShippingMethodsAmasty: function() {
            if(typeof ShippingRateRegistry.clearStorage === 'function') {
                ShippingRateRegistry.clearStorage();
            }
        },

        totals: function () {
            if (Quote.isVirtual() ||
                window.checkoutConfig.activeCarriers && window.checkoutConfig.activeCarriers.length === 0
            ) {
                TotalsProcessor.estimateTotals(Quote.shippingAddress());
            }
        }
    };

});
