<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Plugin\Model;

/**
 * Class Quote
 */
class Quote
{
    /**
     * @var \Magento\Framework\App\ResourceConnection
     */
    protected $resource;

    /**
     * Quote constructor.
     *
     * @param \Magento\Framework\App\ResourceConnection $resource
     */
    public function __construct(
        \Magento\Framework\App\ResourceConnection $resource
    ) {
        $this->resource = $resource;
    }

    /**
     * @param \Magento\Quote\Model\Quote $subject
     * @param callable                   $proceed
     *
     * @return mixed
     */
    public function aroundCollectTotals(
        \Magento\Quote\Model\Quote $subject,
        callable $proceed
    ) {
        if ($subject->getId() && $subject->getTriggerRecollect() == 1) {
            $connection = $this->resource->getConnection('checkout');
            $quoteTable = $this->resource->getTableName('quote', 'checkout');
            $query = "UPDATE `" . $quoteTable . "` SET trigger_recollect = 0 WHERE entity_id = " . (int)$subject->getId();
            $connection->query($query);
        }

        $result = $proceed();
        $subject->setTriggerRecollect(0);

        return $result;
    }
}
