<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Model\System\Config;

use Geissweb\Euvat\Helper\Configuration;
use Magento\Config\Block\System\Config\Form\Field;
use Magento\Framework\Data\Form\Element\AbstractElement;

/**
 * Class Extension
 */
class Extension extends Field
{
    /**
     * @var Configuration
     */
    public $configHelper;

    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param Configuration                           $configHelper
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        Configuration $configHelper
    ) {
        parent::__construct($context);
        $this->configHelper = $configHelper;
    }

    /**
     * Retrieve element HTML markup
     *
     * @param AbstractElement $element
     * @return string
     */
    protected function _getElementHtml(AbstractElement $element)
    {
        $setupUrl = $this->getUrl('euvat/setup');
        return '<div>' . $this->getModuleVersion() . ' |
<a href="https://www.geissweb.de/knowledge-base.html" target="_blank">' . __('Knowledge Base') . '</a> |
<a href="https://www.geissweb.de/helpdesk/ticket/" target="_blank">' . __('Support') . '</a> |
<a href="' . $setupUrl . '">' . __('Run Setup') . '</a>
</div>' . $this->getSysCheckHtml();
    }

    protected function getModuleVersion()
    {
        $sysInfo = $this->configHelper->getSystemInformation();
        return $sysInfo['version'];
    }

    /**
     * @return string
     */
    protected function getSysCheckHtml()
    {
        $sysCheckResult = '<br/>';
        if (!extension_loaded('soap')) {
            $sysCheckResult .= '<span style="color:red">PHP SOAP extension not loaded!</span><br/>';
        }
        if (!extension_loaded('curl')) {
            $sysCheckResult .= '<span style="color:red">PHP CURL extension not loaded!</span>';
        }
        return $sysCheckResult;
    }
}
