<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Controller\Vatnumber;

use Geissweb\Euvat\Helper\Configuration;
use Geissweb\Euvat\Helper\VatNumber\Formatter;
use Geissweb\Euvat\Logger\Logger;
use Geissweb\Euvat\Validator\Service as ValidatorService;
use Magento\Framework\App\Action\Context;
use Magento\Framework\Controller\Result\Json as JsonResult;
use Magento\Framework\Controller\Result\Raw as RawResult;
use Magento\Framework\Controller\Result\Redirect as RedirectResult;
use Magento\Framework\Controller\ResultFactory;
use Magento\Framework\Data\Form\FormKey\Validator;

/**
 * Class Validation
 * Executes the validation and gives JSON back
 * Todo refactor when deprecation of Magento\Framework\App\Action\Action has come true
 */
class Validation extends \Magento\Framework\App\Action\Action
{
    /**
     * @var Context
     */
    public $context;

    /**
     * @var Logger
     */
    public $logger;

    /**
     * Validator for Formkey
     * @var Validator
     */
    protected $_formKeyValidator;

    /**
     * @var Configuration
     */
    public $configHelper;
    /**
     * @var ValidatorService
     */
    private $validator;
    /**
     * @var Formatter
     */
    private $formatter;

    /**
     * Constructor
     *
     * @param Context $context
     * @param ValidatorService $validator
     * @param Validator $formKeyValidator
     * @param Configuration $configHelper
     * @param Logger $logger
     */
    public function __construct(
        Context $context,
        ValidatorService $validator,
        Validator $formKeyValidator,
        Configuration $configHelper,
        Formatter $formatter,
        Logger $logger
    ) {
        parent::__construct($context);
        $this->context = $context;
        $this->_formKeyValidator = $formKeyValidator;
        $this->configHelper = $configHelper;
        $this->logger = $logger;
        $this->validator = $validator;
        $this->formatter = $formatter;
    }

    /**
     * Execute VAT number validation
     * @return JsonResult|RawResult
     * @throws \SoapFault
     */
    public function execute()
    {
        if ($this->getRequest()->getMethod() !== 'POST'
            || !$this->getRequest()->isXmlHttpRequest()
            || !$this->_formKeyValidator->validate($this->getRequest())
        ) {
            $this->logger->debug("Aborting Controller: Request()->getMethod(): " . $this->getRequest()->getMethod());
            $this->logger->debug("Request()->isXmlHttpRequest(): " . $this->getRequest()->isXmlHttpRequest());
            $this->logger->debug("FormKey result: " . $this->_formKeyValidator->validate($this->getRequest()));
            /** @var \Magento\Framework\Controller\Result\Raw $resultRaw */
            $resultRaw = $this->resultFactory->create(ResultFactory::TYPE_RAW);
            $resultRaw->setContents('This action is not allowed.');
            return $resultRaw->setHttpResponseCode(400);
        }

        $vatNumber = $this->getRequest()->getPost('vat_number');
        $data = $this->formatter->splitVatNumber($vatNumber, true);
        $response = $this->validator->validate($data['cc'], $data['number']);

        return $this->resultFactory->create(ResultFactory::TYPE_JSON)->setData($response);
    }
}
