<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Controller\Adminhtml\Setup;

use Geissweb\Euvat\Model\Setup\Tax;
use Magento\Backend\App\Action\Context;
use Magento\Framework\Controller\Result\Redirect;
use Magento\Framework\Message\Manager;

/**
 * Class Setup
 * Executes the setup
 */
class Setup extends \Magento\Backend\App\Action
{
    /**
     * Authorization level of a basic admin session
     *
     * @see _isAllowed()
     */
    const ADMIN_RESOURCE = 'Geissweb_Euvat::setup';

    /**
     * @var Tax
     */
    private $euvatSetupTax;

    /**
     * @var Context
     */
    private $context;

    /**
     * Initialize Group Controller
     *
     * @param Context $context
     * @param Tax     $euvatSetupTax
     * @param Manager  $messageManager
     *
     * @internal param \Magento\Framework\View\Result\PageFactory $resultPageFactory
     */
    public function __construct(
        Context $context,
        Tax $euvatSetupTax,
        Manager $messageManager
    ) {
        $this->euvatSetupTax  = $euvatSetupTax;
        $this->messageManager = $messageManager;
        $this->context        = $context;
        parent::__construct($context);
    }

    /**
     * @return Redirect
     */
    public function execute()
    {
        try {
            $resultRedirect = $this->resultRedirectFactory->create();
            $resultRedirect->setPath('*/*');
            $post = $this->getRequest()->getParams();

            if (empty($post)) {
                $this->messageManager->addNotice(__('Can not execute the Setup without data.'));
            } else {
                /** @var Tax $setup */
                $setup = $this->euvatSetupTax->runSetup($post['general']);
                if ($setup) {
                    $this->euvatSetupTax->clearConfigCache();
                    $this->messageManager->addSuccessMessage(
                        __('EU VAT Enhanced Setup completed successfully. Please now apply your settings.')
                    );
                    $resultRedirect->setPath('adminhtml/system_config/edit/', ['section' => 'euvat']);
                }
            }
            return $resultRedirect;
        } catch (\Exception $e) {
            $this->messageManager->addException($e, $e->getMessage());
        }
    }

    /**
     * @return bool
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed(self::ADMIN_RESOURCE);
    }
}
