<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Controller\Adminhtml\Setup;

/**
 * Class Skip
 * Skipaction when user decides to not use the setup
 */
class Skip extends \Magento\Backend\App\Action
{
    /**
     * Authorization level of a basic admin session
     *
     * @see _isAllowed()
     */
    const ADMIN_RESOURCE = 'Geissweb_Euvat::setup';

    /**
     * @var \Magento\Framework\Registry
     */
    private $_coreRegistry;

    /**
     * @var \Geissweb\Euvat\Model\Setup\TaxFactory
     */
    private $euvatSetupTaxFactory;

    /**
     * @var \Magento\Framework\Message\Manager
     */
    protected $messageManager;

    /**
     * Initialize Group Controller
     *
     * @param \Magento\Backend\App\Action\Context               $context
     * @param \Magento\Framework\Registry                       $coreRegistry
     * @param \Geissweb\Euvat\Model\Setup\TaxFactory            $euvatSetupTaxFactory
     * @param \Magento\Framework\Message\Manager       $messageManager
     *
     * @internal param \Magento\Backend\Model\Session $backendSession
     */
    public function __construct(
        \Magento\Backend\App\Action\Context $context,
        \Magento\Framework\Registry $coreRegistry,
        \Geissweb\Euvat\Model\Setup\TaxFactory $euvatSetupTaxFactory,
        \Magento\Framework\Message\Manager $messageManager
    ) {
        $this->_coreRegistry = $coreRegistry;
        $this->euvatSetupTaxFactory = $euvatSetupTaxFactory;
        $this->messageManager = $messageManager;

        parent::__construct($context);
    }

    /**
     * Skip Action and redirect
     *
     * @return \Magento\Framework\Controller\Result\Redirect
     */
    public function execute()
    {
        $this->euvatSetupTaxFactory->create()->setIsInstalled();

        $this->messageManager->addNoticeMessage(
            __('Automated Setup has been skipped. Please apply your settings now.')
        );

        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('adminhtml/system_config/edit/', ['section' => 'euvat']);

        return $resultRedirect;
    }
}
