<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Api\Data;

interface ValidationInterface
{
    const VAT_IS_VALID = 'vat_is_valid';
    const VALIDATION_ID = 'validation_id';
    const REQUEST_MESSAGE = 'request_message';
    const VAT_ID = 'vat_id';
    const HANDLE = 'handle';
    const VAT_TRADER_ADDRESS = 'vat_trader_address';
    const VAT_REQUEST_ID = 'vat_request_id';
    const VAT_REQUEST_DATE = 'vat_request_date';
    const VAT_TRADER_NAME = 'vat_trader_name';
    const VAT_REQUEST_SUCCESS = 'vat_request_success';

    /**
     * Get validation_id
     * @return string|null
     */

    public function getValidationId();

    /**
     * Set validation_id
     * @param string $validationId
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setValidationId($validationId);

    /**
     * Get vat_id
     * @return string|null
     */

    public function getVatId();

    /**
     * Set vat_id
     * @param string $vat_id
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setVatId($vat_id);

    /**
     * Get vat_is_valid
     * @return string|null
     */

    public function getVatIsValid();

    /**
     * Set vat_is_valid
     * @param string $vat_is_valid
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setVatIsValid($vat_is_valid);

    /**
     * Get vat_request_success
     * @return string|null
     */

    public function getVatRequestSuccess();

    /**
     * Set vat_request_success
     * @param string $vat_request_success
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setVatRequestSuccess($vat_request_success);

    /**
     * Get vat_request_id
     * @return string|null
     */

    public function getVatRequestId();

    /**
     * Set vat_request_id
     * @param string $vat_request_id
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setVatRequestId($vat_request_id);

    /**
     * Get vat_request_date
     * @return string|null
     */

    public function getVatRequestDate();

    /**
     * Set vat_request_date
     * @param string $vat_request_date
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setVatRequestDate($vat_request_date);

    /**
     * Get vat_trader_name
     * @return string|null
     */

    public function getVatTraderName();

    /**
     * Set vat_trader_name
     * @param string $vat_trader_name
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setVatTraderName($vat_trader_name);

    /**
     * Get vat_trader_address
     * @return string|null
     */

    public function getVatTraderAddress();

    /**
     * Set vat_trader_address
     * @param string $vat_trader_address
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setVatTraderAddress($vat_trader_address);

    /**
     * Get handle
     * @return string|null
     */

    public function getHandle();

    /**
     * Set handle
     * @param string $handle
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setHandle($handle);

    /**
     * Get request_message
     * @return string|null
     */

    public function getRequestMessage();

    /**
     * Set request_message
     * @param string $request_message
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface
     */

    public function setRequestMessage($request_message);
}
