<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Api\Data;

/**
 * Interface ValidationSearchResultsInterface
 */
interface ValidationSearchResultsInterface extends \Magento\Framework\Api\SearchResultsInterface
{
    /**
     * Get Validation list.
     * @return \Geissweb\Euvat\Api\Data\ValidationInterface[]
     */

    public function getItems();

    /**
     * Set vat_id list.
     * @param \Geissweb\Euvat\Api\Data\ValidationInterface[] $items
     * @return $this
     */

    public function setItems(array $items);
}
