<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Model\System;

/**
 * Class SetupNotice
 */
class SetupNotice implements \Magento\Framework\Notification\MessageInterface //extends \Magento\Backend\Block\Template
{
    /**
     * @var \Magento\Framework\UrlInterface
     */
    protected $_urlBuilder;

    /**
     * @var \Magento\Framework\AuthorizationInterface
     */
    protected $_authorization;

    /**
     * @var \Geissweb\Euvat\Helper\Configuration
     */
    private $configHelper;

    /**
     * @param \Magento\Framework\AuthorizationInterface $authorization
     * @param \Magento\Framework\UrlInterface           $urlBuilder
     * @param \Geissweb\Euvat\Helper\Configuration      $configHelper
     */
    public function __construct(
        \Magento\Framework\AuthorizationInterface $authorization,
        \Magento\Framework\UrlInterface $urlBuilder,
        \Geissweb\Euvat\Helper\Configuration $configHelper
    ) {
        $this->_authorization = $authorization;
        $this->_urlBuilder = $urlBuilder;
        $this->configHelper = $configHelper;
    }

    /**
     * Retrieve unique message identity
     *
     * @return string
     */
    public function getIdentity()
    {
        return hash('SHA256', 'cache'.implode(':', ['geissweb','euvat','setup']));
    }

    /**
     * Check whether
     *
     * @return bool
     */
    public function isDisplayed()
    {
        return $this->_authorization->isAllowed('Geissweb_Euvat::setup') && !$this->configHelper->getIsInstalled();
    }

    /**
     * Retrieve message text
     *
     * @return string
     */
    public function getText()
    {
        $message = __('EU VAT Enhanced has been installed.');
        $message .= __(' ');
        $url = $this->_urlBuilder->getUrl('euvat/setup/index'); //adminhtml/euvat_setup
        $message .= __('Run the <a href="%1">Configuration Helper</a>', $url);
        $message .= __(' - or - ');
        $url = $this->_urlBuilder->getUrl('euvat/setup/skip');
        $message .= __('If taxes and VAT are already configured <a href="%1">skip the helper</a>.', $url);
        return $message;
    }

    /**
     * Retrieve message severity
     *
     * @return int
     */
    public function getSeverity()
    {
        return \Magento\Framework\Notification\MessageInterface::SEVERITY_MAJOR;
    }
}
