<?php
$description = $block->getData('description');
$onChange   = $block->getData('onChange');
$elementId  = $block->getData('elementId');
?>
<?php if ($description): ?>
    <div class="optimize-description">
        <?= $description ?>
    </div>
    <style>
        .optimize-description {
            padding: .5rem 1rem;
            background: #f1f1f1;
            font-size: 12px;
        }
    </style>
<?php endif ?>

<?php if ($onChange): ?>
    <div class="optimize-on-change" id="onChange<?= $elementId ?>">
        <?= $onChange ?>
    </div>
    <style>
        .optimize-on-change {
            display: none;
            padding: .5rem 1rem;
            background: #E86777;
            font-size: 12px;
            color: #fff;
        }
    </style>
    <script>
        require(['jquery'], function ($) {
            $('#<?=$elementId ?>').on('change', function () {
                $('#onChange<?=$elementId ?>').show();
            });
        });
    </script>
<?php endif ?>
