<?php if (false !== $data = $block->getDetailPushForward()): ?>
	<script data-ommit="true">

		<?php
		/**
		 * AdWords Dynamic Remarketing
		 */
		?>
		
		window.google_tag_params.ecomm_pagetype 	= '<?php echo $data->google_tag_params['ecomm_pagetype'] ?>';
		window.google_tag_params.ecomm_category 	= '<?php echo $data->google_tag_params['ecomm_category'] ?>';
		window.google_tag_params.ecomm_prodid		= '<?php echo $data->google_tag_params['ecomm_prodid'] ?>';
		window.google_tag_params.ecomm_totalvalue 	=  <?php echo $data->google_tag_params['ecomm_totalvalue'] ?>;
		window.google_tag_params.returnCustomer 	=  <?php echo $block->getHelper()->getIsReturnCustomer() ?>;

		<?php if ($block->getHelper()->supportDynx()): ?>

		window.google_tag_params.dynx_pagetype 		= 'offerdetail';
		window.google_tag_params.dynx_itemid 		= window.google_tag_params.ecomm_prodid;
		window.google_tag_params.dynx_totalvalue 	= window.google_tag_params.ecomm_totalvalue;
		
		<?php endif ?>
		
		<?php
		/**
		 * Detail push
		 */
		?>

		AEC.Cookie.detail(<?php echo $data->push ?>).push(dataLayer, false);

		<?php
		/**
		 * Private browser fallback
		 */
		?>

		dataLayerTransport.push(<?php echo $data->push ?>);
		
		<?php
		/**
		 * Grouped product map
		 */
		?>
		
		window.G = <?php echo $data->group ?>;

		<?php if ($block->getHelper()->facebook()): ?>

    		if (AEC.Const.COOKIE_DIRECTIVE)
    		{
    			AEC.CookieConsent.queue(() => 
    			{
        			if ('undefined' !== typeof fbq)
        			{
    					fbq('track', 'ViewContent', <?php echo $data->fbq ?>);
        			}
    			});
    		}
    		else 
    		{
        		if ('undefined' !== typeof fbq)
        		{
    				fbq('track', 'ViewContent', <?php echo $data->fbq ?>);
        		}
    		}
			
		<?php endif ?>
	</script>

<?php endif ?>
