<script data-ommit="true">

    document.addEventListener("DOMContentLoaded", () => 
    {
    	require(['jquery'],function($)
    	{
    		(function($, dataLayer)
    		{
    			var events = 
    			{
    				addToCart: function()
    				{
    					<?php if ($block->getHelper()->useOnHandler()):?>
    
    					AEC.ajax(this, dataLayer);
    					
    					<?php endif ?>
    					
    				},
    				removeFromCart: function()
    				{
    					<?php if ($block->getHelper()->useOnHandler()):?>
    
    					AEC.remove(this, dataLayer);
    					
    					<?php endif ?>
    					
    				},
    				productClick: function()
    				{
    					<?php if ($block->getHelper()->useOnHandler()):?>
    
    					AEC.click(this, dataLayer);
    					
    					<?php endif ?>
    					
    				},
    				addToWishlist: function()
    				{
    					<?php if ($block->getHelper()->useOnHandler()):?>
    
    					AEC.wishlist(this, dataLayer);
    					
    					<?php endif ?>
    					
    				},
    				addToCompare: function()
    				{
    					<?php if ($block->getHelper()->useOnHandler()):?>
    
    					AEC.compare(this, dataLayer);
    					
    					<?php endif ?>
    					
    				},
    				addToCartSwatch: function()
    				{
    					<?php if ($block->getHelper()->useOnHandler()):?>
    
    					AEC.ajaxSwatch(this, dataLayer);
    					
    					<?php endif ?>
    				}
    			};
    
    			var b = function(events)
    			{
    				$.each(events, function(event, callback)
    				{
    					var elements = $('[data-event]').filter(function()
    					{
    						return $(this).data('event') == event;
    					});
    
    					elements.each(function()
    					{
    						$(this).off('click.ec').on('click.ec', callback);
    					});
    				});
    			};
    
    			<?php
    			/**
    			 * Bind events
    			 */
    			?>
    			
    			b(events);
    
    			<?php
    			/**
    			 * Bind events (for ajax loaded content);
    			 */
    			?>

    			(function(events)
    			{
    				$(document).ajaxComplete(function( event, request, settings ) 
    				{
    					b(events);
    				});
    			})(events);
    			
    		})($, dataLayer);
    	});
    });
    
</script>