<?php

/**
 * @var \Mirasvit\OptimizeJs\Block\Frontend\YoutubeBlock $block
 */

?>

<style>
    * {
        padding:0;
        margin:0;
        overflow:hidden
    }
    html,body {
        height:100%
    }
    img,span {
        position:absolute;
        width:100%;
        top:0;
        bottom:0;
        margin:auto
    }
    span {
        height:1.5em;
        text-align:center;
        font:48px/1.5 sans-serif;
        color:white;
        text-shadow:0 0 0.5em black
    }
</style>
<a href=<?php echo $block->getData('src_link') ?> >
    <img src=<?php echo $block->getData('img_link') ?> alt='<?php echo $block->getData('img_alt') ?>'>
    <span>▶</span>
</a>

