<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Block;

use Geissweb\Euvat\Helper\Configuration;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Element\Template\Context;

/**
 * @property array layoutProcessors
 */
class Vatfield extends Template
{
    /**
     * @var Configuration
     */
    private $config;

    /**
     * Constructor
     *
     * @param Context       $context
     * @param Configuration $config
     * @param array         $layoutProcessors
     * @param array         $data
     */
    public function __construct(
        Context $context,
        Configuration $config,
        $layoutProcessors = [],
        $data = []
    ) {
        parent::__construct($context, $data);

        $this->config = $config;
        $this->layoutProcessors = $layoutProcessors;
    }

    /**
     * Get JS Layout
     * @return string
     */
    public function getJsLayout()
    {
        foreach ($this->layoutProcessors as $processor) {
            $this->jsLayout = $processor->process($this->jsLayout);
        }
        return parent::getJsLayout();
    }

    /**
     * Gets system config
     * @return Configuration
     */
    public function getConfigHelper()
    {
        return $this->config;
    }
}
