/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

define([
    'ko',
    'jquery',
    'mage/storage',
    'mage/url',
    'Magento_Checkout/js/action/get-totals'
], function(ko, $, storage,urlBuilder, getTotalsAction) {

        'use strict';
        return function () {
            var serviceUrl = urlBuilder.build('euvat/checkout/recollect');
            return storage.post(
                serviceUrl,
                JSON.stringify({})
            ).done(
                function(response) {
                    if(response) {
                        var deferred = $.Deferred();
                        getTotalsAction([], deferred);
                    }
                }
            );/*.fail(
                function (response) {
                    //var error = JSON.parse(response.responseText);
                }
            );*/
        }
    }
);