<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Helper\Compat;

/**
 * Class UnserializerFactory
 */
class UnserializerFactory
{

    /**
     * @var \Magento\Framework\ObjectManagerInterface
     */
    protected $objectManager;

    /**
     * JsonFactory constructor.
     *
     * @param \Magento\Framework\ObjectManagerInterface $objectManager
     */
    public function __construct(
        \Magento\Framework\ObjectManagerInterface $objectManager
    ) {
        $this->objectManager = $objectManager;
    }

    /**
     * \Magento\Framework\Serialize\Serializer\Json introduced in 2.2.0
     * \Magento\Framework\Unserialize\Unserialize is deprecated
     *
     * @param array $data
     *
     * @return mixed
     */
    public function create(array $data = [])
    {
        if (class_exists(\Magento\Framework\Serialize\Serializer\Json::class)) {
            $instanceName =  \Magento\Framework\Serialize\Serializer\Json::class;
        } else {
            $instanceName = \Magento\Framework\Unserialize\Unserialize::class;
        }
        return $this->objectManager->create($instanceName, $data);
    }
}
